/*
 * Copyright (c) 2017-2018 Richard Braun.
 * Copyright (c) 2017 Jerko Lenstra.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#include <errno.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include <lpc17xx.h>
#include <lib/cbuf.h>
#include <lib/macros.h>

#include "cpu.h"
#include "uart.h"
#include "thread.h"

#define UART0_IRQ               5

#define UART_BUFFER_SIZE        16

#if !ISP2(UART_BUFFER_SIZE)
#error "invalid buffer size"
#endif

/*
 * Data shared between threads and the interrupt handler.
 *
 * Interrupts and preemption must be disabled when accessing these data.
 */
static uint8_t uart_buffer[UART_BUFFER_SIZE];
static struct cbuf uart_cbuf;
static struct thread *uart_waiter;

static void
uart_irq_handler(void *arg)
{
    uint32_t reg;
    bool spurious;
    int error;

    (void)arg;

    spurious = true;

    for (;;) {
        reg = LPC_UART0->lsr;

        if (!(reg & UART_RDR_MASK)) {
            break;
        }

        spurious = false;
        reg = LPC_UART0->tx_rx_dll;
        error = cbuf_pushb(&uart_cbuf, (uint8_t)reg, false);

        if (error) {
            printf("uart: error: buffer full\n");
            break;
        }
    }

    if (!spurious) {
        thread_wakeup(uart_waiter);
    }
}

static void
uart_tx_wait(void)
{
    uint32_t lsr;

    for (;;) {
        lsr = LPC_UART0->lsr;

        if (lsr & UART_THRE_MASK) {
            break;
        }
    }
}

void
uart_setup(void)
{
    cbuf_init(&uart_cbuf, uart_buffer, sizeof(uart_buffer));

    /* Set the UART0 clock to 12.5MHz */
    LPC_SC->PCLKSEL0 |= (3 << 6);

    /* Set DLAB */
    LPC_UART0->lcr |= (1 << UART_DLAB_SHIFT);

    /* These numbers were manually generated by an algorithm in the
     * LPC17xx datahseet. */
    LPC_UART0->tx_rx_dll = 5;
    LPC_UART0->fdr = (14 << UART_MULVAL_SHIFT) | (5 << UART_DIVADDVAL_SHIFT);

    /* Enable the UART FIFO. */
    LPC_UART0->iir_fcr = (1 << UART_FIFO_EN_SHIFT);

    /* Set pins P0.2, P0.3 to TXD0 and RXD0 respectively. */
    LPC_PINCON->PINSEL0 |= (1 << 4) | (1 << 6);

    /* /\* Disable DLAB. *\/ */
    LPC_UART0->lcr &= (0 << UART_DLAB_SHIFT);

    /* Enable interrupts for receive data available */
    LPC_UART0->ier_dlm = 1;

    /* Set 8-bit word length */
    LPC_UART0->lcr |= 3;

    cpu_irq_register(UART0_IRQ, uart_irq_handler, NULL);
}


static void
uart_write_byte(uint8_t byte)
{
    uart_tx_wait();
    LPC_UART0->tx_rx_dll = byte;
}

void
uart_write(uint8_t byte)
{
    if (byte == '\n') {
        uart_write_byte('\r');
    }

    uart_write_byte(byte);
}

int
uart_read(uint8_t *byte)
{
    uint32_t primask;
    int error;

    primask = thread_preempt_disable_intr_save();

    if (uart_waiter) {
        error = EBUSY;
        goto out;
    }

    for (;;) {
        error = cbuf_popb(&uart_cbuf, byte);

        if (!error) {
            break;
        }

        uart_waiter = thread_self();
        thread_sleep();
        uart_waiter = NULL;
    }

    error = 0;

out:
    thread_preempt_enable_intr_restore(primask);

    return error;
}
